### ISSUE TITLE
rake dummy:app failed: TypeError: superclass mismatch for class Command

### ISSUE THREAD

**Issue by JuanitoFatas** [Courseware/rails-dummy#9]
Just install rails-dummy gem and add `require 'rails/dummy/tasks'` to rake file then run `rake dummy:app` yields the following:

```
$ rake dummy:app
rake aborted!
TypeError: superclass mismatch for class Command
/Users/Juan/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:2:in `<class:Thor>'
/Users/Juan/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:1:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:1:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/group.rb:1:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/generators.rb:4:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.0/gems/rails-dummy-0.0.4/lib/rails/dummy/generator.rb:2:in `<top (required)>'
/Users/Juan/.gem/ruby/2.2.0/gems/rails-dummy-0.0.4/lib/rails/dummy/tasks.rb:1:in `<top (required)>'
```

**Comment by JuanitoFatas** [comment]
Sorry need to add `bundle exec`.

**Comment by stas** [comment]
Cool :+1:
